title: Arctica1의 창고
email: your-email@example.com
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""  # 이 부분을 비워두세요
url: "https://my-blog-dusky-six.vercel.app"  # Vercel에서 제공한 URL로 변경하세요
twitter_username: ㅁㅁㅁㅁ
github_username:  arctica1

# Build settings
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Minima specific settings
minima:
  skin: classic
